version: "3.9"

x-common-variables: &common-variables
  POSTGRES_USER: stayvacay
  POSTGRES_PASSWORD: stayvacay
  POSTGRES_DB: stayvacay
  POSTGRES_SERVER: db

services:
  web:
    build: .
    environment:
      *common-variables
    ports:
      - 8089:8089
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:latest
    environment:
      *common-variables
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
